# ============================================================
#  mpvnet.conf — options spécifiques à mpv.net
#  (séparé de mpv.conf qui contient les options libmpv standard)
#  Doc : https://github.com/mpvnet-player/mpv.net/wiki
# ============================================================

# Interface en français (utilise Locale/fr/LC_MESSAGES/mpvnet.mo)
language=fr
